name: Daily News Fetch

on:
  schedule:
    # Runs at 3 AM and 3 PM UTC daily
    - cron: "0 3,15 * * *"
  workflow_dispatch:       # Allows manual triggering

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Update config with API keys
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        ALPHAVANTAGE_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
      run: |
        sed -i "s/alphavantage_key = .*/alphavantage_key = $ALPHAVANTAGE_KEY/" config.ini
        sed -i "s/newsapi_key = .*/newsapi_key = $NEWSAPI_KEY/" config.ini
   
    - name: Run NewsAPI script
      run: |
        python newsapi_article_aggregator.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'dparedesi@uni.pe'
        git add output/*
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update news files"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
