name: Daily News Fetch

on:
  schedule:
    # Runs at different times of the day
    - cron: "0 5,7,11,17,19 * * *"
    # Runs every 6 hours
    #- cron: "0 */6 * * *"
  workflow_dispatch:       # Allows manual triggering as well

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Update config with API keys
      env:
        NEWSAPI_KEY1: ${{ secrets.NEWSAPI_KEY1 }}
        NEWSAPI_KEY2: ${{ secrets.NEWSAPI_KEY2 }}
        NEWSAPI_KEY3: ${{ secrets.NEWSAPI_KEY3 }}
        NEWSAPI_KEY4: ${{ secrets.NEWSAPI_KEY4 }}
        NEWSAPI_KEY5: ${{ secrets.NEWSAPI_KEY5 }}
        ALPHAVANTAGE_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
      run: |
        sed -i "s/newsapi_key1 = .*/newsapi_key1 = $NEWSAPI_KEY1/" config.ini
        sed -i "s/newsapi_key2 = .*/newsapi_key2 = $NEWSAPI_KEY2/" config.ini
        sed -i "s/newsapi_key3 = .*/newsapi_key3 = $NEWSAPI_KEY3/" config.ini
        sed -i "s/newsapi_key4 = .*/newsapi_key4 = $NEWSAPI_KEY4/" config.ini
        sed -i "s/newsapi_key5 = .*/newsapi_key5 = $NEWSAPI_KEY5/" config.ini
        sed -i "s/alphavantage_key = .*/alphavantage_key = $ALPHAVANTAGE_KEY/" config.ini

    - name: Run NewsAPI script
      run: |
        python newsapi_article_aggregator.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'dparedesi@uni.pe'
        git add output/* last_used_api_key.txt
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update news files and last used API key"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
